config/routes.rb
WhyDeliver::Application.routes.draw do

  get "/login" => "sessions#new", :as => 'sign_in'
  post "/login" => "sessions#create", :as => 'sign_in'
  get "/sign-up" => "merchants#new", :as => 'sign_up'
  get "/sign_out" => "sessions#destroy", :as => "sign_out"

  get "/pages/map"
  get "/pages/dashboard", :as => "dashboard"

  root :to => "pages#landing"

  resources :statuses

  get "/orders/callback" => "orders#callback"
  resources :orders
  
  resources :transporters

  resources :merchants
  
  get "/dashboard" => "pages#dashboard"

  get "/fakeiphone" => "pages#fakeiphone", :as => 'fakeiphone'
  get "/ipsum" => "pages#ipsum"
  get "/form" => "pages#form"

  scope "api" do
    get "/order" => "api#get_order"
    post "/order" => "api#create_order"

    get "/orders/:id" => "api#get_orders"

    get "/get_transporter" => "api#get_transporter"
    get "/get_merchant" => "api#get_merchant"
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.haml
= form_for @status do |f|
  - if @status.errors.any?
    #error_explanation
      %h2= "#{pluralize(@status.errors.count, "error")} prohibited this status from being saved:"
      %ul
        - @status.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :message
    = f.text_field :message
  .actions
    = f.submit 'Save'

app/views/statuses/edit.html.haml
%h1 Editing status

= render 'form'

= link_to 'Show', @status
\|
= link_to 'Back', statuses_path

app/views/statuses/index.html.haml
%h1 Listing statuses

%table
  %tr
    %th Message
    %th
    %th
    %th

  - @statuses.each do |status|
    %tr
      %td= status.message
      %td= link_to 'Show', status
      %td= link_to 'Edit', edit_status_path(status)
      %td= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Status', new_status_path

app/views/statuses/new.html.haml
%h1 New status

= render 'form'

= link_to 'Back', statuses_path

app/views/statuses/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @status.message

= link_to 'Edit', edit_status_path(@status)
\|
= link_to 'Back', statuses_path