config/routes.rb
WhyDeliver::Application.routes.draw do

  get "/login" => "sessions#new", :as => 'sign_in'
  post "/login" => "sessions#create", :as => 'sign_in'
  get "/sign-up" => "merchants#new", :as => 'sign_up'
  get "/sign_out" => "sessions#destroy", :as => "sign_out"

  get "/pages/map"
  get "/pages/dashboard", :as => "dashboard"

  root :to => "pages#landing"

  resources :statuses

  get "/orders/callback" => "orders#callback"
  resources :orders
  
  resources :transporters

  resources :merchants
  
  get "/dashboard" => "pages#dashboard"

  get "/fakeiphone" => "pages#fakeiphone", :as => 'fakeiphone'
  get "/ipsum" => "pages#ipsum"
  get "/form" => "pages#form"

  scope "api" do
    get "/order" => "api#get_order"
    post "/order" => "api#create_order"

    get "/orders/:id" => "api#get_orders"

    get "/get_transporter" => "api#get_transporter"
    get "/get_merchant" => "api#get_merchant"
  end

end

app/models/transporter.rb
class Transporter < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :current_lat, :current_long, :email, :first_name, :last_name, :phone, :available
end

app/controllers/transporters_controller.rb
class TransportersController < ApplicationController
  # GET /transporters
  # GET /transporters.json
  def index
    @transporters = Transporter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transporters }
    end
  end

  # GET /transporters/1
  # GET /transporters/1.json
  def show
    @transporter = Transporter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transporter }
    end
  end

  # GET /transporters/new
  # GET /transporters/new.json
  def new
    @transporter = Transporter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transporter }
    end
  end

  # GET /transporters/1/edit
  def edit
    @transporter = Transporter.find(params[:id])
  end

  # POST /transporters
  # POST /transporters.json
  def create
    @transporter = Transporter.new(params[:transporter])

    respond_to do |format|
      if @transporter.save
        format.html { redirect_to @transporter, notice: 'Transporter was successfully created.' }
        format.json { render json: @transporter, status: :created, location: @transporter }
      else
        format.html { render action: "new" }
        format.json { render json: @transporter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transporters/1
  # PUT /transporters/1.json
  def update
    @transporter = Transporter.find(params[:id])

    respond_to do |format|
      if @transporter.update_attributes(params[:transporter])
        render :nothing => true
      else
        render :nothing => true
      end
    end
  end

  # DELETE /transporters/1
  # DELETE /transporters/1.json
  def destroy
    @transporter = Transporter.find(params[:id])
    @transporter.destroy

    respond_to do |format|
      format.html { redirect_to transporters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transporters_helper.rb
module TransportersHelper
end

app/views/transporters/_form.html.haml
= form_for @transporter do |f|
  - if @transporter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transporter.errors.count, "error")} prohibited this transporter from being saved:"
      %ul
        - @transporter.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.number_field :phone
  .field
    = f.label :current_lat
    = f.text_field :current_lat
  .field
    = f.label :current_long
    = f.text_field :current_long
  .actions
    = f.submit 'Save'

app/views/transporters/edit.html.haml
%h1 Editing transporter

= render 'form'

= link_to 'Show', @transporter
\|
= link_to 'Back', transporters_path

app/views/transporters/index.html.haml
%h1 Listing transporters

%table
  %tr
    %th First name
    %th Last name
    %th Email
    %th Phone
    %th Current lat
    %th Current long
    %th
    %th
    %th

  - @transporters.each do |transporter|
    %tr
      %td= transporter.first_name
      %td= transporter.last_name
      %td= transporter.email
      %td= transporter.phone
      %td= transporter.current_lat
      %td= transporter.current_long
      %td= link_to 'Show', transporter
      %td= link_to 'Edit', edit_transporter_path(transporter)
      %td= link_to 'Destroy', transporter, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Transporter', new_transporter_path

app/views/transporters/new.html.haml
%h1 New transporter

= render 'form'

= link_to 'Back', transporters_path

app/views/transporters/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @transporter.first_name
%p
  %b Last name:
  = @transporter.last_name
%p
  %b Email:
  = @transporter.email
%p
  %b Phone:
  = @transporter.phone
%p
  %b Current lat:
  = @transporter.current_lat
%p
  %b Current long:
  = @transporter.current_long

= link_to 'Edit', edit_transporter_path(@transporter)
\|
= link_to 'Back', transporters_path