config/routes.rb
WhyDeliver::Application.routes.draw do

  get "/login" => "sessions#new", :as => 'sign_in'
  post "/login" => "sessions#create", :as => 'sign_in'
  get "/sign-up" => "merchants#new", :as => 'sign_up'
  get "/sign_out" => "sessions#destroy", :as => "sign_out"

  get "/pages/map"
  get "/pages/dashboard", :as => "dashboard"

  root :to => "pages#landing"

  resources :statuses

  get "/orders/callback" => "orders#callback"
  resources :orders
  
  resources :transporters

  resources :merchants
  
  get "/dashboard" => "pages#dashboard"

  get "/fakeiphone" => "pages#fakeiphone", :as => 'fakeiphone'
  get "/ipsum" => "pages#ipsum"
  get "/form" => "pages#form"

  scope "api" do
    get "/order" => "api#get_order"
    post "/order" => "api#create_order"

    get "/orders/:id" => "api#get_orders"

    get "/get_transporter" => "api#get_transporter"
    get "/get_merchant" => "api#get_merchant"
  end

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base

  require 'open-uri'

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :password_digest, :remember_me
  attr_accessible :address, :email, :lat, :long, :name, :phone, :stripe_customer_id, :last_four_digits
  
  has_secure_password
  
  before_create :geolocate_address
  
  private
  def geolocate_address
    url = "http://maps.googleapis.com/maps/api/geocode/json?address=#{self.address.gsub(/\s/, '+')}&sensor=true"
    response = JSON.parse(open(url).read)
    self.lat = response["results"][0]["geometry"]["location"]["lat"]
    self.long = response["results"][0]["geometry"]["location"]["lng"]
  end

  has_many :orders

end

app/controllers/merchants/registrations_controller.rb
class Merchants::RegistrationsController < Devise::RegistrationsController
  
  def create
    @merchant = Merchant.new(params[:merchant])
    session[:merchant_id] = @merchant.id
    
    raise session[:merchant_id].to_yaml
    Stripe.api_key = STRIPE_TEST_SECRET
    token = params[:stripeToken]

    customer = Stripe::Customer.create(
      :card => token,
      :description => "Andrew Chambers"
    )
     
    raise "Check if Customer Created" 
    # charge = Stripe::Charge.create(
    #   :amount => 2000,
    #   :currency => "usd",
    #   :card => token,
    #   :description => "payinguser@example.com"
    # )
  end
  
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  # before_filter :require_merchant, :except => ['new', 'create']

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @merchants }
    end
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
    @merchant = Merchant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @merchant }
    end
  end

  # GET /merchants/new
  # GET /merchants/new.json
  def new
    @merchant = Merchant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @merchant }
    end
  end

  # GET /merchants/1/edit
  def edit
    @merchant = Merchant.find(params[:id])
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(params[:merchant])
    session[:merchant_id] = @merchant.id
    
    Stripe.api_key = STRIPE_TEST_SECRET
    token = params[:stripeToken]
    
    
    unless @merchant.stripe_customer_id.present? customer = Stripe::Customer.create(
      :card => token,
      :email => @merchant.email
    )
    end
    
    @merchant.update_attributes(:stripe_customer_id => customer["id"])
     
    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render json: @merchant, status: :created, location: @merchant }
      else
        format.html { render action: "new" }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /merchants/1
  # PUT /merchants/1.json
  def update
    @merchant = Merchant.find(params[:id])

    respond_to do |format|
      if @merchant.update_attributes(params[:merchant])
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant = Merchant.find(params[:id])
    @merchant.destroy

    respond_to do |format|
      format.html { redirect_to merchants_url }
      format.json { head :no_content }
    end
  end
  
  private
  def require_merchant
    @merchant = Merchant.find(session[:merchant_id])
  end
  
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.haml
.wrapper
  = form_for @merchant, :class => "grid pad group create-merchant-form" do |f|
    - if @merchant.errors.any?
      #error_explanation
        %h2= "#{pluralize(@merchant.errors.count, "error")} prohibited this merchant from being saved:"
        %ul
          - @merchant.errors.full_messages.each do |msg|
            %li= msg

    .col-1
      = f.text_field :name
      = f.label :name
    .col-1-2
      = f.text_field :email
      = f.label :email
    .col-1-2
      = f.number_field :phone
      = f.label :phone
    .col-1
      = f.text_field :address
      = f.label :address
    .col-1-2
      = f.password_field :password
      = f.label :password
    .col-1-2
      = f.password_field :password_confirmation
      = f.label :password_confirmation
    .col-1
      %input.card-number{:autocomplete => "off", :size => "20", :type => "text"}
      %label Card Number
    .col-1-2
      
      %input.card-cvc{:autocomplete => "off", :size => "4", :type => "text"}
      %label CVC
    .col-1-2
      .col-1-2
        %input.card-expiry-month{:size => "2", :type => "text"}/
        %label Expiration (MM)
      .col-1-2
        %input.card-expiry-year{:size => "4", :type => "text"}/
        %label Expiration (YYYY)
        
    .actions
      = f.submit 'Create Account', :class => 'submit-button create-merchant-btn'

app/views/merchants/edit.html.haml
%h1 Editing merchant

= render 'form'

= link_to 'Show', @merchant
\|
= link_to 'Back', merchants_path

app/views/merchants/index.html.haml
%h1 Listing merchants

%table
  %tr
    %th Name
    %th Email
    %th Phone
    %th Address
    %th Lat
    %th Long
    %th
    %th
    %th

  - @merchants.each do |merchant|
    %tr
      %td= merchant.name
      %td= merchant.email
      %td= merchant.phone
      %td= merchant.address
      %td= merchant.lat
      %td= merchant.long
      %td= link_to 'Show', merchant
      %td= link_to 'Edit', edit_merchant_path(merchant)
      %td= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Merchant', new_merchant_path

app/views/merchants/new.html.haml
= render 'form'

%script
  Stripe.setPublishableKey("#{STRIPE_TEST_PUBLISH_KEY}");

app/views/merchants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @merchant.name
%p
  %b Email:
  = @merchant.email
%p
  %b Phone:
  = @merchant.phone
%p
  %b Address:
  = @merchant.address
%p
  %b Lat:
  = @merchant.lat
%p
  %b Long:
  = @merchant.long

= link_to 'Edit', edit_merchant_path(@merchant)
\|
= link_to 'New Order', new_order_path(:merchant_id => @merchant.id)